### ISSUE TITLE
Issues with files having the same filename

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/ome-tiff-pyramid#2]
Consider the following input dataset

```
➜  test tree .
.
├── 1
│   └── multi-channel.ome.tif
├── 2
│   └── multi-channel.ome.tif
├── 3
│   └── multi-channel.ome.tif
├── 4
│   └── multi-channel.ome.tif
├── 5
│   └── multi-channel.ome.tif
└── MxIF-metadata.tsv

5 directories, 6 files
```

Because all the files have the same name, the pipeline produces the following files

```
multi-channel.ome.tif
multi-channel.ome.tif_1
multi-channel.ome.tif_1_2
multi-channel.ome.tif_1_2_3
multi-channel.ome.tif_1_2_3_4
```

which to my understanding is not correct. Shouldn't it produce output that looks like `multi-channel_1_2_3_4.ome.tif` instead of `multi-channel.ome.tif_1_2_3_4`.

**Comment by mruffalo** [comment]
Fixed in 89ec05d1d681fbcb6e72051ff0b6decc3f8d5051.
