### ISSUE TITLE
Save .n5 files to output folder

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/ome-tiff-pyramid#3]
For each OME.TIFF in the input dataset, the original pipeline was supposed to create a `.n5` file. 

Can the pipeline be updated so that it saves the `.n5` to the output folder?

**Comment by mruffalo** [comment]
Returning raw directories was implemented in 89ec05d1d681fbcb6e72051ff0b6decc3f8d5051, and zipping the `n5` directories was added in 4132fc89ede407e1eb6ef81fb05112728c42b9ef.
